### PR TITLE
Set gold amount

### PR DESCRIPTION
**Pull request by filsdelamour**
Dear m0n4,

I really appreciated your Python program. I would like to help enriching it with a few new functionalities, for instance set the gold amount value there. I kept your functionalities and arguments, just extending them.
I would be honored if you accept this extension and argument parsing rewrite.

Best regards,
filsdelamour.

### CODE REVIEW

**Comment by m0n4** [comment]
I didn't think anyone would use it so I'm even more surprised to receive a PR.
It's a very good addition and it's much better coded.
I was more interested in the reversing part than the coding and it shows.
Thank you for your contribution

**Comment by filsdelamour** [comment]
Thank you for acceptance. I will propose more stuff soon, e.g., set one item value. I also plan to create a Qt-based graphical interface, if I have time.
Best regards.

**Comment by m0n4** [comment]
Amazing, this game came out 10 years ago (in japan) it's crazy.
the gem part is not finished but you must have seen it.
Maybe it deserves to be looked at in more detail.

**Comment by filsdelamour** [comment]
Indeed I went into this "old" Wii version due to more recent port to the Switch console. As I use emulation on Linux without a top10 graphical card, I saw that the Wii version was suitable for me and rather nice to look and play with upgraded HD textures packs. Your Python program is thus really comfortable to use on Linux and well coded enough to be easy to understand.

I haven't looked into gems part, as I was more interested in colony 6 reconstruction. Thank you for the pointing this out.

**Pull request merged**
